### ISSUE TITLE
IntraHTML does not support HTML comments

### ISSUE THREAD

**Issue by vinyll** [rndme/intraHTML#2]
When writing a comment like:

```html
<div>
  <-- This is a comment -->
  <h3>title</h3>
</div>
```

The comment will be rendered as text and displayed.

**Comment by rndme** [comment]
Yes, this was a choice I made to keep the codebase (much) simpler and compact. Had I supported comments, I would have to support commented-out broken markup like imbalanced tags as well as a far more complex interpretation of "<" characters, which degraded performance. Since HTML comments aren't _needed_, they were left out.
